apiVersion: carto.run/v1alpha1
kind: ClusterSourceTemplate
metadata:
  name: api-compliance-test-pipeline
spec:
  urlPath: .status.outputs.url
  revisionPath: .status.outputs.revision

  template:
    apiVersion: carto.run/v1alpha1
    kind: Runnable
    metadata:
      name: $(workload.metadata.name)$
    spec:
      serviceAccountName: $(workload.spec.serviceAccountName)$
      runTemplateRef:
        name: tekton-api-compliance-test-taskrun

      selector:
        resource:
          apiVersion: tekton.dev/v1beta1
          kind: Task
        matchingLabels:
          task: api-compliance-test

      inputs:
        source-url: $(sources.source.url)$
        source-revision: $(sources.source.revision)$