apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  labels:
    task: api-compliance-test
  name: api-compliance-test
spec:
  params:
  - name: source-url
  - name: source-revision
  steps:
  - name: test
    image: maven:3-openjdk-11
    script: |-
      cd `mktemp -d`
      wget -qO- $(params.source-url) | tar xvz -m
      mvn integration-test
      cat target/openapi.json | tee /tekton/results/openapi-spec.json
  - image: harbor.emea.end2end.link/vodafone/api-test-engine  
    name: api-compliance-test
    script: |-
      node src/index.js -g TMF620 4.1.0
      node src/index.js -c TMF620-4.1.0-WithExtensions.swagger.json /tekton/results/openapi-spec.json