apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  labels:
    task: api-compliance-test
  name: api-compliance-test
  namespace: default
spec:
  params:
  - name: source-url
  - name: source-revision
  steps:
  - image: openapitools/openapi-diff
    name: api-compliance-test
    script: |-
      cd `mktemp -d`
      wget -qO- $(params.source-url) | tar xvz -m

      java -jar /app/openapi-diff.jar https://raw.githubusercontent.com/tsalm-pivotal/tm-forum-nodejs/main/config/open-api-spec.yaml  src/main/resources/openapi.yaml --fail-on-incompatible

     
      