apiVersion: carto.run/v1alpha1
kind: ClusterSourceTemplate
metadata:
  name: api-compliance-test-pipeline
spec:
  urlPath: .status.outputs.url
  revisionPath: .status.outputs.revision

  template:
    apiVersion: carto.run/v1alpha1
    kind: Runnable
    metadata:
      name: $(workload.metadata.name)$-api-compliance-test
    spec:
      serviceAccountName: $(workload.spec.serviceAccountName)$
      runTemplateRef:
        name: tekton-api-compliance-test-taskrun
        kind: ClusterRunTemplate
      inputs:
        source-url: $(sources.source.url)$
        source-revision: $(sources.source.revision)$